

create table public.product_imeis (
  id bigint generated by default as identity not null,
  product_id bigint not null,
  store_id bigint not null,
  imei text not null,
  created_at timestamp with time zone null default now(),
  constraint product_imeis_pkey primary key (id),
  constraint product_imeis_product_id_fkey foreign KEY (product_id) references dynamic_product (id) on delete CASCADE,
  constraint product_imeis_imei_check check ((imei <> ''::text))
) TABLESPACE pg_default;

create index IF not exists idx_product_imeis_store_imei on public.product_imeis using btree (store_id, imei) TABLESPACE pg_default;

create index IF not exists idx_product_imeis_product on public.product_imeis using btree (product_id) TABLESPACE pg_default;